<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2019-08-14 07:44:40
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'all-70384b9f4432fbfbc96c73dec96c03be.js',
        ],
        'css' => [
            'all-06120b90d1a8e354222b23607758d14c.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
];