<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2019-08-17 08:58:36
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'all-8e19afda429fc6a3b15037b0f56c9c9e.js',
        ],
        'css' => [
            'all-751dcb24840f95a58177b262a7b75341.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
];