<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "project".
 *
 * @property int $id 自增id
 * @property string $title 标题
 * @property string $description 描述
 * @property string $belong_to 描述
 * @property string $content 内容
 * @property string $pic 图片
 * @property int $sort 排序
 * @property int $cid 排序
 * @property int $created_at 创建时间
 * @property int $updated_at 更新时间
 */
class Project extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'project';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content', 'description'], 'required'],
            [['sort', 'cid'], 'integer'],
            [['title'], 'string', 'max' => 50],
            [['pic'],'string','max' => 255],
            [['belong_to'],'string','max'=>100]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'pic' => '封面图片',
            'description' => '描述',
            'belong_to' => '所属公司',
            'content' => '内容',
            'sort' => '排序',
            'cid' => '所属栏目',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ];
    }

    public function getCategory()
    {
        return $this->hasOne(ProjectCategory::className(),['id' => 'cid']); // TODO: Change the autogenerated stub
    }
}
